@echo off
setlocal EnableDelayedExpansion

REM Default target; override with first argument if provided (e.g., create-env.bat .env1)
set "TARGET_FILE=.env"
if not "%~1"=="" set "TARGET_FILE=%~1"

if exist "%TARGET_FILE%" (
  echo %TARGET_FILE% already exists.
  choice /C YN /M "Overwrite?"
  if errorlevel 2 (
    echo Cancelled.
    exit /b 0
  )
)

call :prompt_var MIRO_CLIENT_ID "your_miro_client_id" "required" 1
call :prompt_var MIRO_CLIENT_SECRET "your_miro_client_secret" "required" 1
call :prompt_var MIRO_REDIRECT_URI "http://localhost:8000/callback" "default local callback" 0
call :prompt_var MIRO_SCOPES "boards:read boards:write account:read" "default scopes" 0
call :prompt_var MIRO_BOARD_ID "your_miro_board_id" "required" 1
call :prompt_var MIRO_REFRESH_TOKEN "" "required - obtain this first via web login" 1
call :prompt_var MIRO_ACCESS_TOKEN "" "optional - leave blank; will be obtained after web login using refresh token" 0

> "%TARGET_FILE%" (
  echo # Generated by create-env.bat. Fill real values and keep secret.
  echo MIRO_CLIENT_ID="!MIRO_CLIENT_ID!"
  echo MIRO_CLIENT_SECRET="!MIRO_CLIENT_SECRET!"
  echo MIRO_REDIRECT_URI="!MIRO_REDIRECT_URI!"
  echo MIRO_SCOPES="!MIRO_SCOPES!"
  echo MIRO_BOARD_ID="!MIRO_BOARD_ID!"
  echo MIRO_REFRESH_TOKEN="!MIRO_REFRESH_TOKEN!"
  echo MIRO_ACCESS_TOKEN="!MIRO_ACCESS_TOKEN!"
)

echo Created %TARGET_FILE%. Review values before running the app.
exit /b 0

:prompt_var
set "VAR_NAME=%~1"
set "DEFAULT=%~2"
set "NOTE=%~3"
set "REQUIRED=%~4"
set "%VAR_NAME%="

echo.
if defined NOTE (
  echo [%VAR_NAME%] %NOTE%
) else (
  echo [%VAR_NAME%]
)
if defined DEFAULT (
  echo Default: %DEFAULT%
) else (
  echo Default: (empty)
)

:ask_input
set "INPUT="
set /p "INPUT=Enter %VAR_NAME% (press Enter to use default/leave empty): "
if not defined INPUT if defined DEFAULT set "INPUT=%DEFAULT%"
if "%REQUIRED%"=="1" if not defined INPUT (
  echo Value is required. Please enter a value.
  goto ask_input
)
set "%VAR_NAME%=%INPUT%"
goto :eof
